# Generated by Django 3.0.6 on 2020-07-21 20:42

import anavibase.model.positive_big_int
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anaviexpert', '0001_initial'),
        ('website', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', anavibase.model.positive_big_int.PositiveAutoBigInt(primary_key=True, serialize=False)),
                ('name_fr', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('sentence_index', models.PositiveIntegerField(default=0, help_text='Field to know in wich sentence aspect was extracted')),
                ('start_to', models.PositiveIntegerField(default=0)),
                ('end_to', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', anavibase.model.positive_big_int.PositiveAutoBigInt(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('text_fr', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.Hotel')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.WebSite')),
            ],
        ),
        migrations.CreateModel(
            name='Polarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertComment',
            fields=[
                ('id', anavibase.model.positive_big_int.PositiveAutoBigInt(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anaviexpert.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='AspectPolarity',
            fields=[
                ('id', anavibase.model.positive_big_int.PositiveAutoBigInt(primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Aspect')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaviexpert.Expert')),
                ('polarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Polarity')),
            ],
        ),
        migrations.AddField(
            model_name='aspect',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment'),
        ),
    ]
