# Generated by Django 3.0.6 on 2020-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
