# Generated by Django 3.0.6 on 2020-07-22 04:31

import anavibase.model.positive_big_int
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectpolarity',
            name='aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Aspect'),
        ),
        migrations.CreateModel(
            name='AspectEn',
            fields=[
                ('id', anavibase.model.positive_big_int.PositiveAutoBigInt(primary_key=True, serialize=False)),
                ('name_fr', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=255)),
                ('sentence_index', models.PositiveIntegerField(default=0, help_text='Field to know in wich sentence aspect was extracted')),
                ('start_to', models.PositiveIntegerField(default=0)),
                ('end_to', models.PositiveIntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='aspectpolarity',
            name='aspecten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.AspectEn'),
        ),
    ]
