# Generated by Django 3.0.6 on 2020-07-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anaviexpert', '0001_initial'),
        ('comment', '0003_aspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AspectPolarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Aspect')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anaviexpert.Expert')),
                ('polarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Polarity')),
            ],
        ),
    ]
