# Generated by Django 3.0.6 on 2020-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_aspectpolarity_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
